fix

diff --git a/static/client/Dockerfile b/static/client/Dockerfile
--- a/static/client/Dockerfile
+++ b/static/client/Dockerfile
@@ -11,11 +11,11 @@ COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
 
 # Install dependencies based on the preferred package manager
 RUN \
-  if [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
-  elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install --frozen-lockfile; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
+  #if [ -f yarn.lock ]; then yarn install --frozen-lockfile; \
+  [ -f package-lock.json ]; then npm ci;
+  #elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm install --frozen-lockfile; \
+  #else echo "Lockfile not found." && exit 1; \
+  #fi
 
 # Rebuild the source code only when needed
 FROM base AS builder
